### ISSUE TITLE
Add FontAwesome or other icon font

### ISSUE THREAD

**Issue by maurizi** [azavea/pwd-fishway#61]
## Overview

We have a variety of icons we'll be using in the application.
In the past we have typically used FontAwesome for this purpose, though we could use a different icon font instead.

### Tasks

- [x] Add font icon set with all icons needed for the project
- [x] Replace any current text or unicode characters in use with font icons
- [ ] Integrate font icon set into Webpack build (if necessary)

**Comment by maurizi** [comment]
Done in #65
